CURRENT_RELEASE = 105

ENSEMBL_RELEASE_LIST = ['105', '104', '103', '102', '101', '100', '99', '98', '97', '96', '95', '94', '93', '92', '91',
                        '90', '89', '88', '87', '86', '80', '77', '75', '54']

SPECIES_LIST = ['acanthochromis polyacanthus', 'accipiter nisus', 'ailuropoda melanoleuca', 'amazona collaria',
                'amphilophus citrinellus', 'amphiprion ocellaris', 'amphiprion percula', 'anabas testudineus',
                'anas platyrhynchos', 'anas platyrhynchos platyrhynchos', 'anas zonorhyncha', 'anolis carolinensis',
                'anser brachyrhynchus', 'anser cygnoides', 'aotus nancymaae', 'apteryx haastii', 'apteryx owenii',
                'apteryx rowi', 'aquila chrysaetos chrysaetos', 'astatotilapia calliptera', 'athene cunicularia',
                'balaenoptera musculus', 'betta splendens', 'bison bison bison', 'bos grunniens', 'bos mutus',
                'bos taurus', 'bubo bubo', 'buteo japonicus', 'caenorhabditis elegans', 'cairina moschata domestica',
                'calidris pugnax', 'calidris pygmaea', 'callithrix jacchus', 'callorhinchus milii',
                'camarhynchus parvulus', 'camelus dromedarius', 'canis lupus dingo', 'carassius auratus',
                'carlito syrichta', 'castor canadensis', 'catagonus wagneri', 'catharus ustulatus', 'cavia aperea',
                'cavia porcellus', 'cebus capucinus imitator', 'cercocebus atys', 'cervus hanglu yarkandensis',
                'chelonoidis abingdonii', 'chelydra serpentina', 'chinchilla lanigera', 'chlorocebus sabaeus',
                'choloepus hoffmanni', 'chrysemys picta bellii', 'chrysolophus pictus', 'ciona intestinalis',
                'ciona savignyi', 'clupea harengus', 'colobus angolensis palliatus', 'corvus moneduloides',
                'cottoperca gobio', 'coturnix japonica', 'crocodylus porosus', 'cyanistes caeruleus',
                'cyanoderma ruficeps', 'cyclopterus lumpus', 'cynoglossus semilaevis', 'cyprinodon variegatus',
                'danio rerio', 'dasypus novemcinctus', 'delphinapterus leucas', 'denticeps clupeoides',
                'dicentrarchus labrax', 'dipodomys ordii', 'dromaius novaehollandiae', 'drosophila melanogaster',
                'echeneis naucrates', 'echinops telfairi', 'electrophorus electricus', 'eptatretus burgeri',
                'equus asinus asinus', 'equus caballus', 'erinaceus europaeus', 'erpetoichthys calabaricus',
                'erythrura gouldiae', 'esox lucius', 'falco tinnunculus', 'felis catus', 'ficedula albicollis',
                'fukomys damarensis', 'fundulus heteroclitus', 'gadus morhua', 'gallus gallus', 'gambusia affinis',
                'gasterosteus aculeatus', 'geospiza fortis', 'gopherus agassizii', 'gopherus evgoodei',
                'gorilla gorilla gorilla', 'gouania willdenowi', 'haplochromis burtoni', 'hippocampus comes',
                'homo sapiens', 'hucho hucho', 'ictalurus punctatus', 'ictidomys tridecemlineatus', 'jaculus jaculus',
                'junco hyemalis', 'kryptolebias marmoratus', 'labrus bergylta', 'larimichthys crocea',
                'lates calcarifer', 'laticauda laticaudata', 'latimeria chalumnae', 'lepidothrix coronata',
                'lepisosteus oculatus', 'leptobrachium leishanense', 'lonchura striata domestica', 'loxodonta africana',
                'lynx canadensis', 'macaca fascicularis', 'macaca mulatta', 'macaca nemestrina',
                'malurus cyaneus samueli', 'manacus vitellinus', 'mandrillus leucophaeus', 'marmota marmota marmota',
                'mastacembelus armatus', 'maylandia zebra', 'meleagris gallopavo', 'melopsittacus undulatus',
                'meriones unguiculatus', 'mesocricetus auratus', 'microcebus murinus', 'microtus ochrogaster',
                'mola mola', 'monodelphis domestica', 'monodon monoceros', 'monopterus albus', 'moschus moschiferus',
                'mus caroli', 'mus musculus castaneus', 'mus musculus domesticus', 'mus musculus musculus',
                'mus pahari', 'mus spicilegus', 'mus spretus', 'mustela putorius furo', 'myotis lucifugus',
                'myripristis murdjan', 'naja naja', 'nannospalax galili', 'neogobius melanostomus',
                'neolamprologus brichardi', 'neovison vison', 'nomascus leucogenys', 'notamacropus eugenii',
                'notechis scutatus', 'nothobranchius furzeri', 'nothoprocta perdicaria', 'numida meleagris',
                'ochotona princeps', 'octodon degus', 'oncorhynchus kisutch', 'oncorhynchus mykiss',
                'oncorhynchus tshawytscha', 'oreochromis aureus', 'oreochromis niloticus', 'ornithorhynchus anatinus',
                'oryctolagus cuniculus', 'oryzias javanicus', 'oryzias melastigma', 'oryzias sinensis',
                'otolemur garnettii', 'otus sunia', 'pan paniscus', 'panthera leo', 'panthera pardus',
                'panthera tigris altaica', 'pan troglodytes', 'papio anubis', 'parambassis ranga',
                'paramormyrops kingsleyae', 'parus major', 'pavo cristatus', 'pelodiscus sinensis',
                'pelusios castaneus', 'periophthalmus magnuspinnatus', 'peromyscus maniculatus bairdii',
                'petromyzon marinus', 'phascolarctos cinereus', 'phasianus colchicus', 'phocoena sinus',
                'physeter catodon', 'piliocolobus tephrosceles', 'podarcis muralis', 'poecilia formosa',
                'poecilia latipinna', 'poecilia mexicana', 'poecilia reticulata', 'pogona vitticeps', 'pongo abelii',
                'procavia capensis', 'prolemur simus', 'propithecus coquereli', 'pseudonaja textilis',
                'pteropus vampyrus', 'pundamilia nyererei', 'pygocentrus nattereri', 'rattus norvegicus',
                'rhinolophus ferrumequinum', 'rhinopithecus bieti', 'rhinopithecus roxellana',
                'saccharomyces cerevisiae', 'saimiri boliviensis boliviensis', 'salarias fasciatus', 'salmo salar',
                'salmo trutta', 'salvator merianae', 'sander lucioperca', 'sarcophilus harrisii', 'sciurus vulgaris',
                'scleropages formosus', 'scophthalmus maximus', 'serinus canaria', 'seriola dumerili',
                'seriola lalandi dorsalis', 'sinocyclocheilus anshuiensis', 'sinocyclocheilus grahami',
                'sinocyclocheilus rhinocerous', 'sorex araneus', 'sparus aurata', 'spermophilus dauricus',
                'sphaeramia orbicularis', 'sphenodon punctatus', 'stegastes partitus', 'strigops habroptila',
                'strix occidentalis caurina', 'struthio camelus australis', 'suricata suricatta', 'taeniopygia guttata',
                'takifugu rubripes', 'terrapene carolina triunguis', 'tetraodon nigroviridis', 'theropithecus gelada',
                'tupaia belangeri', 'tursiops truncatus', 'urocitellus parryii', 'ursus americanus', 'ursus maritimus',
                'ursus thibetanus thibetanus', 'varanus komodoensis', 'vicugna pacos', 'vombatus ursinus',
                'vulpes vulpes', 'xenopus tropicalis', 'xiphophorus couchianus', 'xiphophorus maculatus',
                'zalophus californianus', 'zonotrichia albicollis', 'zosterops lateralis melanops']
