# Generated by Django 3.2.6 on 2022-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=80)),
                ('ensembl_version', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
    ]
