# Generated by Django 3.2.6 on 2022-03-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_fetch_run_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetch',
            old_name='run_id',
            new_name='fetch_id',
        ),
    ]
